### ISSUE TITLE
Implement using MessageHandler not HttpClientHandler

### ISSUE THREAD

**Issue by digitalpacman** [JSkimming/MiniProfiler.WebAPI#1]
So an HttpClient only ever uses one HttpClientHandler.  If you already have your system built using a custom HttpClientHandler it is easier to implement using a new message handler instead. Maybe add both options? Instead of forcing a dependency inheritance chain on inheriting your HttpClientHandler. You even named your object a MessageHandler when it's a ClientHandler.

This mainly comes up with someone is using features of WebRequestHandler for WebRequestHandler.ImpersonationLevel or WebRequestHandler.RequestCachePolicy.

Relevant: http://www.asp.net/web-api/overview/advanced/httpclient-message-handlers

**Comment by JSkimming** [comment]
@digitalpacman to be honest I've not done anything with this repo in over two years, it's hugely out of date. If you want to take it and run with it feel free.

**Comment by digitalpacman** [comment]
@JSkimming  Were you able to or are currently still using it?  I'm trying to implement MiniProfiler as a tracer for my suite of microservices.

**Comment by JSkimming** [comment]
It was working at the time, but I don't use MiniProfiler any more, so I can't whether say it works now. It's not a huge amount of effort and is loosely based upon a [MiniProfiler.WCF](https://www.nuget.org/packages/MiniProfiler.WCF).

**Comment by digitalpacman** [comment]
Do you mind me asking what you use now? Is it Glimpse?

**Comment by JSkimming** [comment]
Yeah we use Glimpe in some areas, but it's not n-tier. We also use microservices which we treat independently, and have profiling in each, a mixture of Glimpse and custom profiling.

**Comment by digitalpacman** [comment]
Do you have full end-to-end tracing for your microservices?  That's a goal we're trying to reach.  So a request coming in from our gateway can be tied to every microservice call, every message queued, etc.

**Comment by JSkimming** [comment]
We don't no, as I said, _"it's not n-tier"_, we closely monitor each service.
